[env]
CONFIG_FILE_HOST = { value = "../data/.repocket.config", relative = true }
CREDS_FILE_HOST = { value = "../data/.repocket.key", relative = true }

CONFIG_FILE_RM = "/home/root/.local/share/repocket/.repocket.config"
CREDS_FILE_RM = "/home/root/.local/share/repocket/.repocket.key"

VERBOSITY = "0"


[build]
target = ["aarch64-apple-darwin", "armv7-unknown-linux-gnueabihf"]


[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
  "-C", "link-arg=-march=armv7-a",
  "-C", "link-arg=-marm",
  "-C", "link-arg=-mfpu=neon",
  "-C", "link-arg=-mfloat-abi=hard",
  "-C", "link-arg=-mcpu=cortex-a9",
]
