name: Build Apps

on:
  push:
    branches: [ "main", "wip" ]
    tags:
    - 'v*.*.*'

  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rePocketAuth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build rePocketAuth
      working-directory: ./rePocketAuth
      run: cargo build --release

  build-rePocket:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install rustup targets
      run: rustup target add aarch64-apple-darwin
    - name: Install cross-compilation tools for Rust
      uses: taiki-e/setup-cross-toolchain-action@v1.24.0
      with:
        # Target name
        target: armv7-unknown-linux-gnueabihf
    - name: Build rePocket
      working-directory: ./rePocket
      run: cargo build --release --target armv7-unknown-linux-gnueabihf
    - name: Archive rePocket artifact
      uses: actions/upload-artifact@v4
      with:
        name: rePocket
        path: "target/armv7-unknown-linux-gnueabihf/release/rePocket"

  trigger-release:
    needs: [build-rePocketAuth, build-rePocket]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      actions: read
      contents: write
    uses: ./.github/workflows/release.yml
