name: Release

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  on-success:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Download the binary form the build job
      uses: actions/download-artifact@v4
      with:
        name: rePocket
        path: build/release
        github-token: ${{ github.token }}
    - run: ./scripts/simple_package.sh
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "rePocket.tar.gz"
        tag: "${{ github.ref_name }}"
